name = "portfolio-de"
compatibility_date = "2026-08-01"
pages_build_output_dir = "."

# This binds BLOG_POSTS KV namespace declaratively

[[kv_namespaces]]
binding = "BLOG_POSTS"
id = "e9fe561998244511bcfc4b97058a5a17"
